### ISSUE TITLE
Document fields for CloudWatch logs for SMS deliveries

### ISSUE THREAD

**Issue by AntoineAugusti** [awsdocs/amazon-sns-developer-guide#10]
This issue is about this page https://github.com/awsdocs/amazon-sns-developer-guide/blob/main/doc_source/sms_stats_cloudwatch.md

Would it be possible to document the various fields in the JSON payload?
```json
{
    "notification": {
        "messageId": "34d9b400-c6dd-5444-820d-fbeb0f1f54cf",
        "timestamp": "2016-06-28 00:40:34.558"
    },
    "delivery": {
        "phoneCarrier": "My Phone Carrier",
        "mnc": 270,
        "destination": "+1XXX5550100",
        "priceInUSD": 0.00645,
        "smsType": "Transactional",
        "mcc": 310,
        "providerResponse": "Message has been accepted by phone carrier",
        "dwellTimeMs": 599,
        "dwellTimeMsUntilDeviceAck": 1344
    },
    "status": "SUCCESS"
}

```

Some are self-explanatory but I have a hard time figuring out `mnc` or `mcc` for example

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
