### ISSUE TITLE
ARN for "queue MyQueue in account 123456789012" is incorrect

### ISSUE THREAD

**Issue by erikwhatyouwant** [awsdocs/amazon-sns-developer-guide#11]
ARN for fictional queue "MyQueue" in figure 2 of step 4 incorrectly identifies its service as sns.

```
"Resource":[
      "arn:aws:sns:us-east-2:123456789012:MyQueue"
    ]
```
The formatting for ARNs is
`arn:partition:service:region:account-id:resource-type:resource-id`
https://docs.aws.amazon.com/general/latest/gr/aws-arns-and-namespaces.html

Please update to "arn:aws:sqs:us-east-2:123456789012:MyQueue" to reflect resource correctly.

**Comment by carlasp** [comment]
Dup.
