### ISSUE TITLE
Mobile TTL SDK example conflicts with Message Attribute limitations

### ISSUE THREAD

**Issue by wesQ3** [awsdocs/amazon-sns-developer-guide#19]
`doc_source/sns-ttl.md` includes a Java SDK example with the TTL message attribute and JSON message structure:
```java
PublishRequest publishRequest = new PublishRequest();
publishRequest.setMessageAttributes(messageAttributes);
String message = "{\"title\":\"Test_Title\",\"description\":\"Test_Description\"}";
publishRequest.setMessage(message);
publishRequest.setMessageStructure("json");
```
`doc_source/sns-message-attributes.md` however includes a note:
> Note
> Message attributes are sent only when the message structure is String, not JSON.

I noticed because I am sending messages in JSON structure and would like to add TTL message attributes for APNS, but I don't know how with this limitation. :)

**Comment by wesQ3** [comment]
`doc_source/sns-send-custom-platform-specific-payloads-mobile-devices.md` also includes an example of an AWS CLI call to SNS publish with message attributes and json message structure:
```
aws sns publish \
--endpoint-url https://sns.us-east-1.amazonaws.com \
--target-arn arn:aws:sns:us-east-1:123456789012:endpoint/APNS_PLATFORM/MYAPP/1234a567-bc89-012d-3e45-6fg7h890123i \
--message '{"APNS_PLATFORM":"{\"aps\":{\"content-available\":1}}"}' \
--message-attributes '{ \
  "AWS.SNS.MOBILE.APNS.TOPIC":{"DataType":"String","StringValue":"com.amazon.mobile.messaging.myapp"}, \
  "AWS.SNS.MOBILE.APNS.PRIORITY":{"DataType":"String","StringValue":"10"}}', \
  "AWS.SNS.MOBILE.APNS.PUSH_TYPE":{"DataType":"String","StringValue":"background"} \
--message-structure json
```

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
