### ISSUE TITLE
Live site User Notification Process Overview is a dead-link

### ISSUE THREAD

**Issue by jahanford** [awsdocs/amazon-sns-developer-guide#2]
The link is dead on the live site:
https://docs.aws.amazon.com/sns/latest/dg/sns-user-notifications-process-overview.html

Redirects to toplevel:
https://docs.aws.amazon.com/sns/latest/dg/sns-mobile-application-as-subscriber.html

**Comment by jahanford** [comment]
Also causes a loop in the Previous/Next navigation.

**Comment by shefulloflight** [comment]
This has been fixed and will be on the prod site in ~2 hours. Thank you for your feedback.
