### ISSUE TITLE
Why are SNS messages sent to HTTPS webhook are marked as text/plain and not application/json?

### ISSUE THREAD

**Issue by johnib** [awsdocs/amazon-sns-developer-guide#27]
Hi,

I wonder why JSON messages sent by SNS to HTTPS webhooks have a `content-type` header set to `text/plain` instead of `application/json`?

Thanks

https://github.com/awsdocs/amazon-sns-developer-guide/blob/af277fa007a20e4deeb3b6d267a9a3dc8eaf54da/doc_source/SendMessageToHttp.prepare.md?plain=1#L17

**Comment by laurentpellegrino** [comment]
I was wondering the same Yesterday evening when experimenting with SNS. This prevents most frameworks to unmarshall content to an Object representation automatically. In the same way, the latest client SDK in Java does not include an utility to perform signature verification. This looks crazy/weird for a service in production for years...

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
