### ISSUE TITLE
SNS message attributes to SQS attributes?

### ISSUE THREAD

**Issue by men6288** [awsdocs/amazon-sns-developer-guide#28]
Hi All,

Is there a way to set the SQS attributes from a SNS subscription?

Thanks,
Matthew

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
