### ISSUE TITLE
Unclear wording in SendMessageToHttp.prepare.html

### ISSUE THREAD

**Issue by gareth** [awsdocs/amazon-sns-developer-guide#30]
The phrasing here seems like it's missing some words, possibly after some editing?

> To be clear, Amazon SNS attempts to retry only after a delivery `x-amz-sns-message-id` header field

Could this description be clarified?

https://github.com/awsdocs/amazon-sns-developer-guide/blob/d9e06d45096fc220a5b8a22b55988dcf29c7433e/doc_source/SendMessageToHttp.prepare.md?plain=1#L91

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
