### ISSUE TITLE
Object in key matching does not work

### ISSUE THREAD

**Issue by armeausstahl** [awsdocs/amazon-sns-developer-guide#36]
I've send the following in sns;
```
 {
	"store": {"Type": "String", "Value": "fans"},
	"customer_interests": {"Type": "String.Array", "Value": "[\"baseball\", \"basketball\"]"}
 }
 
```
 
 And set the following policy:
 
 ```
 {
  "store": [
    {
      "exists": true
    }
  ]
}
```

it does not receive the message.

While this works:

```
 {
	"store": "fans",
	"customer_interests": {"Type": "String.Array", "Value": "[\"baseball\", \"basketball\"]"}
 }

```

Is this intended?

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
